### PR TITLE
[Feature] net 6.0 upgrade

### PR DESCRIPTION
**Pull request by Lord-Giganticus**
This PR resolves 1/4th of the changes made in #18.

Changes:
- Updated Kamek.csproj to build for net 6.0 using `upgrade-assistant`

#18 will continue to stay open until all changes are resolved,

### CODE REVIEW

**Comment by RoadrunnerWMC** [comment]
This works fine for me on Ubuntu after installing .NET 6. That said, I notice that [the mwcc-emulator branch (which was just created two days ago) has a different, shorter .NET 6 .csproj.](https://github.com/Treeki/Kamek/blob/mwcc-emulator/Kamek/Kamek.csproj) I'm sure both work fine, but it would be good for the branches to match here -- and of the two files, my guess is that the simpler one is preferable.

Ninji (Treeki) mentioned this on Discord:

> **\<Ninji>** note that I did not use the upgrade assistant, I just copied the .csproj from a new project
> **\<Ninji>** but I don't think the extra properties would be a problem

And while I agree that the extra properties are probably not a problem per se, having slightly different project files in the two branches for no reason seems like a bad idea.

**Comment by Lord-Giganticus** [comment]
> This works fine for me on Ubuntu after installing .NET 6. That said, I notice that [the mwcc-emulator branch (which was just created two days ago) has a different, shorter .NET 6 .csproj.](https://github.com/Treeki/Kamek/blob/mwcc-emulator/Kamek/Kamek.csproj?rgh-link-date=2022-03-08T20%3A14%3A07Z) I'm sure both work fine, but it would be good for the branches to match here -- and of the two files, my guess is that the simpler one is preferable.
> 
> Ninji (Treeki) mentioned this on Discord:
> 
> > **<Ninji>** note that I did not use the upgrade assistant, I just copied the .csproj from a new project
> > **<Ninji>** but I don't think the extra properties would be a problem
> 
> And while I agree that the extra properties are probably not a problem per se, having slightly different project files in the two branches for no reason seems like a bad idea.

Ah, that was probably my mistake, Microsoft's `upgrade-assistant` likes to add a hidden nuget package reference for some reason. I'll update my csproj to match theirs.

**Comment by Lord-Giganticus** [comment]
9447c7f was pushed to simplify it, however i need to keep `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` in the csproj because dotnet core has this thing where not doing that will auto generate assembly info, causing a CS0579 build error with `AssemblyInfo.cs`.

**Comment by RoadrunnerWMC** [comment]
Ah, you're right, I get the same behavior. I should've tested both .csprojs before assuming they work equally well. I'll go ahead and merge this.

**Pull request merged**
