### PR TITLE
Add Dolphin INI support

### PR DESCRIPTION
**Pull request by MasterofGalaxies**
Add support for Dolphin's config files with `-output-dolphin=`.

### CODE REVIEW

**Comment by MasterofGalaxies** [comment]
@RoadrunnerWMC

**Comment by RoadrunnerWMC** [comment]
Hi, is this still useful now that Dolphin supports playing Riivolution patches directly?

**Comment by MasterofGalaxies** [comment]
Not as useful as it was, but I still think there are times where this is preferable.

**Comment by RoadrunnerWMC** [comment]
All right then. Thanks!

**Pull request merged**
