### PR TITLE
[FEATURE] Upgrade Kamek to modern DotNet

### PR DESCRIPTION
**Pull request by Lord-Giganticus**
This PR upgrades the Kamek project to DotNet 6.0 for better speeds and cross-platform compatability.
It also adds the following features:
* Fixes Gecko code error: 02dcf9e
* Adds a github action for auto builds: c579530 and various other commits
* Various code improvements: c1eb5d7
Any suggestions are welcome.

### CODE REVIEW

**Comment by RoadrunnerWMC** [comment]
Nice, thank you!

This PR does several unrelated things. Would you mind splitting it into a few separate PRs for cleanliness and to make it easier to review? Maybe one for .NET 6, another for GitHub Actions, and another for the "various code improvements." The "Gecko code error" is actually already fixed in the current master branch.

**Comment by RoadrunnerWMC** [comment]
Hey, friendly bump since I'm finally actually working on Kamek again. I'd really like to merge these improvements once they're split up. Thanks again for the PR!

**Comment by Lord-Giganticus** [comment]
Ah thanks, I'll be trying to get to that today.

**Comment by Lord-Giganticus** [comment]
#19 has been added for the net6.0 upgrade, other prs will happen tommorow.

**Comment by Lord-Giganticus** [comment]
Going to reopen with the other planned changes/ideas.

**Pull request closed without merging**
