### PR TITLE
Fix issue with GAS binaries (#3)

### PR DESCRIPTION
**Pull request by MasterofGalaxies**

### CODE REVIEW

**Comment by RoadrunnerWMC** [comment]
What's this fixing, exactly? I don't know what a "GAS binary" is...

**Comment by CLF78** [comment]
GAS binaries are binaries compiled with the GNU Assembler.

**Comment by MasterofGalaxies** [comment]
Yes, code assembled with GNU assembler or compiled with GCC. See #3.

This PR fixes this bug:

```
$ cat returnstring.s
lis 3, string@h
ori 3, 3, string@l
blr
string:
.string "string"
$ powerpc-eabi-as -o returnstring.o returnstring.s
$ Kamek returnstring.o -static=0x80001900 -output-riiv=returnstring.xml
Kamek 2.0 by Ninji/Ash Wolf - https://github.com/Treeki/Kamek

adding returnstring.o as object..
linking version default...

Unhandled Exception:
System.IO.InvalidDataException: undefined symbol 
  at Kamek.Linker.ResolveSymbol (Kamek.Elf elf, System.String name) [0x00110] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Linker.ProcessRelaSection (Kamek.Elf elf, Kamek.Elf+ElfSection relocs, Kamek.Elf+ElfSection section, Kamek.Elf+ElfSection symtab) [0x000cc] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Linker.ProcessRelocations () [0x00149] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Linker.DoLink (System.Collections.Generic.Dictionary`2[TKey,TValue] externalSymbols) [0x0008d] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Linker.LinkStatic (System.UInt32 baseAddress, System.Collections.Generic.Dictionary`2[TKey,TValue] externalSymbols) [0x00019] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Program.Main (System.String[] args) [0x004a5] in <84417af72b3544ac8bfbaa14b20da809>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.InvalidDataException: undefined symbol 
  at Kamek.Linker.ResolveSymbol (Kamek.Elf elf, System.String name) [0x00110] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Linker.ProcessRelaSection (Kamek.Elf elf, Kamek.Elf+ElfSection relocs, Kamek.Elf+ElfSection section, Kamek.Elf+ElfSection symtab) [0x000cc] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Linker.ProcessRelocations () [0x00149] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Linker.DoLink (System.Collections.Generic.Dictionary`2[TKey,TValue] externalSymbols) [0x0008d] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Linker.LinkStatic (System.UInt32 baseAddress, System.Collections.Generic.Dictionary`2[TKey,TValue] externalSymbols) [0x00019] in <84417af72b3544ac8bfbaa14b20da809>:0 
  at Kamek.Program.Main (System.String[] args) [0x004a5] in <84417af72b3544ac8bfbaa14b20da809>:0
```

**Comment by RoadrunnerWMC** [comment]
I see. Thanks!

**Pull request merged**
